export const event_photo_gallery = [
  {
    profile_photo: require('../../assets/party/party_1_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_1.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_2_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_2.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_3_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_3.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_4.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_5.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_6.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_7_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_7.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_8.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_9.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_10.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_11.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_12_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_12.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_13_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_13.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_14_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_14.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_4.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5_thumb.webp'),
    profile_photo_close: require('../../assets/party/party_5.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_7_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_12_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_13_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_14_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_7_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_12_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_13_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_14_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_7_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_12_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_13_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_14_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_7_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_12_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_13_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_14_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_7_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11_thumb.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
];


export const event_photo_groups = [
  {
    profile_photo: require('../../assets/groups/group_1.webp'),
    views: '10K',
    name: 'Traveling',
    is_open: true,
    type: 'Tech',
  },
  {
    profile_photo: require('../../assets/groups/group_2.webp'),
    views: '10K',
    name: 'Workout',
    is_open: false,
    type: 'Sport',
  },
  {
    profile_photo: require('../../assets/party/party_3.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: false,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4.webp'),
    views: '10K',
    name: 'Huge Party',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5.webp'),
    views: '10K',
    name: 'Saturday Night Fever!',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6.webp'),
    views: '10K',
    name: 'Drinks',
    is_open: false,
    type: 'Sport',
  },
  {
    profile_photo: require('../../assets/party/party_7.webp'),
    views: '10K',
    name: 'Long Night',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8.webp'),
    views: '10K',
    name: 'Friday Friday Friday',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9.webp'),
    views: '10K',
    name: 'Dance',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10.webp'),
    views: '10K',
    name: 'Underground',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_12.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_13.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_14.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_4.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_5.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_6.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_7.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_8.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_9.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_10.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
  {
    profile_photo: require('../../assets/party/party_11.webp'),
    views: '10K',
    name: 'Friday Slackers',
    is_open: true,
    type: 'Social',
  },
];
